<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            // GUJARAT (Comprehensive List)
            ['name' => 'Ahmedabad', 'state' => 'Gujarat'],
            ['name' => 'Surat', 'state' => 'Gujarat'],
            ['name' => 'Vadodara', 'state' => 'Gujarat'],
            ['name' => 'Rajkot', 'state' => 'Gujarat'],
            ['name' => 'Bhavnagar', 'state' => 'Gujarat'],
            ['name' => 'Jamnagar', 'state' => 'Gujarat'],
            ['name' => 'Gandhinagar', 'state' => 'Gujarat'],
            ['name' => 'Junagadh', 'state' => 'Gujarat'],
            ['name' => 'Gandhidham', 'state' => 'Gujarat'],
            ['name' => 'Anand', 'state' => 'Gujarat'],
            ['name' => 'Navsari', 'state' => 'Gujarat'],
            ['name' => 'Morbi', 'state' => 'Gujarat'],
            ['name' => 'Nadiad', 'state' => 'Gujarat'],
            ['name' => 'Bharuch', 'state' => 'Gujarat'],
            ['name' => 'Mehsana', 'state' => 'Gujarat'],
            ['name' => 'Bhuj', 'state' => 'Gujarat'],
            ['name' => 'Porbandar', 'state' => 'Gujarat'],
            ['name' => 'Palanpur', 'state' => 'Gujarat'],
            ['name' => 'Valsad', 'state' => 'Gujarat'],
            ['name' => 'Vapi', 'state' => 'Gujarat'],
            ['name' => 'Gondal', 'state' => 'Gujarat'],
            ['name' => 'Veraval', 'state' => 'Gujarat'],
            ['name' => 'Godhra', 'state' => 'Gujarat'],
            ['name' => 'Patan', 'state' => 'Gujarat'],
            ['name' => 'Kalol', 'state' => 'Gujarat'],
            ['name' => 'Dahod', 'state' => 'Gujarat'],
            ['name' => 'Botad', 'state' => 'Gujarat'],
            ['name' => 'Amreli', 'state' => 'Gujarat'],
            ['name' => 'Deesa', 'state' => 'Gujarat'],
            ['name' => 'Jetpur', 'state' => 'Gujarat'],
            ['name' => 'Surendranagar', 'state' => 'Gujarat'],
            ['name' => 'Ankleshwar', 'state' => 'Gujarat'],
            ['name' => 'Himatnagar', 'state' => 'Gujarat'],
            ['name' => 'Modasa', 'state' => 'Gujarat'],
            ['name' => 'Palitana', 'state' => 'Gujarat'],
            ['name' => 'Sidhyapur', 'state' => 'Gujarat'],
            ['name' => 'Savarkundla', 'state' => 'Gujarat'],
            ['name' => 'Unjha', 'state' => 'Gujarat'],
            ['name' => 'Visnagar', 'state' => 'Gujarat'],
            ['name' => 'Viramgam', 'state' => 'Gujarat'],
            ['name' => 'Kadi', 'state' => 'Gujarat'],
            ['name' => 'Halol', 'state' => 'Gujarat'],
            ['name' => 'Khambhat', 'state' => 'Gujarat'],
            ['name' => 'Vaso', 'state' => 'Gujarat'],
            ['name' => 'Borsad', 'state' => 'Gujarat'],
            ['name' => 'Petlad', 'state' => 'Gujarat'],
            ['name' => 'Dholka', 'state' => 'Gujarat'],
            ['name' => 'Bardoli', 'state' => 'Gujarat'],
            ['name' => 'Mahuva', 'state' => 'Gujarat'],
            ['name' => 'Sihor', 'state' => 'Gujarat'],
            ['name' => 'Kapaadvanj', 'state' => 'Gujarat'],
            ['name' => 'Thasra', 'state' => 'Gujarat'],
            ['name' => 'Vijapur', 'state' => 'Gujarat'],
            ['name' => 'Idar', 'state' => 'Gujarat'],
            ['name' => 'Prantij', 'state' => 'Gujarat'],
            ['name' => 'Talod', 'state' => 'Gujarat'],
            ['name' => 'Anjar', 'state' => 'Gujarat'],
            ['name' => 'Mundra', 'state' => 'Gujarat'],
            ['name' => 'Mandvi', 'state' => 'Gujarat'],
            ['name' => 'Rapar', 'state' => 'Gujarat'],
            ['name' => 'Bhachau', 'state' => 'Gujarat'],
            ['name' => 'Songadh', 'state' => 'Gujarat'],
            ['name' => 'Vyara', 'state' => 'Gujarat'],
            ['name' => 'Anbilara', 'state' => 'Gujarat'],
            ['name' => 'Ahwa', 'state' => 'Gujarat'],
            ['name' => 'Saputara', 'state' => 'Gujarat'],
            ['name' => 'Bilimora', 'state' => 'Gujarat'],
            ['name' => 'Dharampur', 'state' => 'Gujarat'],
            ['name' => 'Umbergaon', 'state' => 'Gujarat'],
            ['name' => 'Karjan', 'state' => 'Gujarat'],
            ['name' => 'Padra', 'state' => 'Gujarat'],
            ['name' => 'Dabhoi', 'state' => 'Gujarat'],
            ['name' => 'Limbdi', 'state' => 'Gujarat'],
            ['name' => 'Wadhwan', 'state' => 'Gujarat'],
            ['name' => 'Dhrangadhra', 'state' => 'Gujarat'],
            ['name' => 'Bagodra', 'state' => 'Gujarat'],
            ['name' => 'Sanand', 'state' => 'Gujarat'],
            ['name' => 'Bavla', 'state' => 'Gujarat'],
            ['name' => 'Dhandhuka', 'state' => 'Gujarat'],
            ['name' => 'Barwala', 'state' => 'Gujarat'],
            ['name' => 'Vallabhipur', 'state' => 'Gujarat'],
            ['name' => 'Gariadhar', 'state' => 'Gujarat'],
            ['name' => 'Talaja', 'state' => 'Gujarat'],
            ['name' => 'Alang', 'state' => 'Gujarat'],
            ['name' => 'Jafarabad', 'state' => 'Gujarat'],
            ['name' => 'Rajula', 'state' => 'Gujarat'],
            ['name' => 'Lathi', 'state' => 'Gujarat'],
            ['name' => 'Babra', 'state' => 'Gujarat'],
            ['name' => 'Dwarka', 'state' => 'Gujarat'],
            ['name' => 'Khambhalia', 'state' => 'Gujarat'],
            ['name' => 'Okha', 'state' => 'Gujarat'],
            ['name' => 'Somnath', 'state' => 'Gujarat'],
            ['name' => 'Talala', 'state' => 'Gujarat'],
            ['name' => 'Una', 'state' => 'Gujarat'],
            ['name' => 'Kodinar', 'state' => 'Gujarat'],
            ['name' => 'Sutrapada', 'state' => 'Gujarat'],
            ['name' => 'Dhoraji', 'state' => 'Gujarat'],
            ['name' => 'Upleta', 'state' => 'Gujarat'],
            ['name' => 'Gondal', 'state' => 'Gujarat'],
            ['name' => 'Jasdan', 'state' => 'Gujarat'],
            ['name' => 'Morbi', 'state' => 'Gujarat'],
            ['name' => 'Wankaner', 'state' => 'Gujarat'],
            ['name' => 'Tankara', 'state' => 'Gujarat'],
            ['name' => 'Maliya', 'state' => 'Gujarat'],
            ['name' => 'Radhanpur', 'state' => 'Gujarat'],
            ['name' => 'Sami', 'state' => 'Gujarat'],
            ['name' => 'Harij', 'state' => 'Gujarat'],
            ['name' => 'Chanasma', 'state' => 'Gujarat'],
            ['name' => 'Dhanera', 'state' => 'Gujarat'],
            ['name' => 'Tharad', 'state' => 'Gujarat'],
            ['name' => 'Vav', 'state' => 'Gujarat'],
            ['name' => 'Lakhni', 'state' => 'Gujarat'],
            ['name' => 'Bhabhar', 'state' => 'Gujarat'],
            ['name' => 'Bayad', 'state' => 'Gujarat'],
            ['name' => 'Dhansura', 'state' => 'Gujarat'],
            ['name' => 'Malpur', 'state' => 'Gujarat'],
            ['name' => 'Meghraj', 'state' => 'Gujarat'],
            ['name' => 'Bhiloda', 'state' => 'Gujarat'],
            ['name' => 'Lunawada', 'state' => 'Gujarat'],
            ['name' => 'Balasinor', 'state' => 'Gujarat'],
            ['name' => 'Santrampur', 'state' => 'Gujarat'],
            ['name' => 'Kadana', 'state' => 'Gujarat'],
            ['name' => 'Virpur', 'state' => 'Gujarat'],
            ['name' => 'Shehera', 'state' => 'Gujarat'],
            ['name' => 'Morva Hadaf', 'state' => 'Gujarat'],
            ['name' => 'Zalod', 'state' => 'Gujarat'],
            ['name' => 'Limkheda', 'state' => 'Gujarat'],
            ['name' => 'Devgadh Baria', 'state' => 'Gujarat'],
            ['name' => 'Rajpipla', 'state' => 'Gujarat'],
            ['name' => 'Dediapada', 'state' => 'Gujarat'],
            ['name' => 'Sagbara', 'state' => 'Gujarat'],
            ['name' => 'Netrang', 'state' => 'Gujarat'],
            ['name' => 'Jambusar', 'state' => 'Gujarat'],
            ['name' => 'Amod', 'state' => 'Gujarat'],
            ['name' => 'Vagra', 'state' => 'Gujarat'],
            ['name' => 'Hansot', 'state' => 'Gujarat'],
            ['name' => 'Olpad', 'state' => 'Gujarat'],
            ['name' => 'Mangrol', 'state' => 'Gujarat'],
            ['name' => 'Mandvi (Surat)', 'state' => 'Gujarat'],
            ['name' => 'Kamrej', 'state' => 'Gujarat'],
            ['name' => 'Palsana', 'state' => 'Gujarat'],
            ['name' => 'Choryasi', 'state' => 'Gujarat'],

            // MAHARASHTRA (Comprehensive List)
            ['name' => 'Mumbai', 'state' => 'Maharashtra'],
            ['name' => 'Pune', 'state' => 'Maharashtra'],
            ['name' => 'Nagpur', 'state' => 'Maharashtra'],
            ['name' => 'Thane', 'state' => 'Maharashtra'],
            ['name' => 'Pimpri-Chinchwad', 'state' => 'Maharashtra'],
            ['name' => 'Nashik', 'state' => 'Maharashtra'],
            ['name' => 'Kalyan-Dombivli', 'state' => 'Maharashtra'],
            ['name' => 'Vasai-Virar', 'state' => 'Maharashtra'],
            ['name' => 'Aurangabad', 'state' => 'Maharashtra'],
            ['name' => 'Navi Mumbai', 'state' => 'Maharashtra'],
            ['name' => 'Solapur', 'state' => 'Maharashtra'],
            ['name' => 'Mira-Bhayandar', 'state' => 'Maharashtra'],
            ['name' => 'Bhiwandi', 'state' => 'Maharashtra'],
            ['name' => 'Amravati', 'state' => 'Maharashtra'],
            ['name' => 'Nanded', 'state' => 'Maharashtra'],
            ['name' => 'Kolhapur', 'state' => 'Maharashtra'],
            ['name' => 'Akola', 'state' => 'Maharashtra'],
            ['name' => 'Panvel', 'state' => 'Maharashtra'],
            ['name' => 'Ulhasnagar', 'state' => 'Maharashtra'],
            ['name' => 'Sangli', 'state' => 'Maharashtra'],
            ['name' => 'Malegaon', 'state' => 'Maharashtra'],
            ['name' => 'Jalgaon', 'state' => 'Maharashtra'],
            ['name' => 'Latur', 'state' => 'Maharashtra'],
            ['name' => 'Dhule', 'state' => 'Maharashtra'],
            ['name' => 'Ahmednagar', 'state' => 'Maharashtra'],
            ['name' => 'Chandrapur', 'state' => 'Maharashtra'],
            ['name' => 'Parbhani', 'state' => 'Maharashtra'],
            ['name' => 'Ichalkaranji', 'state' => 'Maharashtra'],
            ['name' => 'Jalna', 'state' => 'Maharashtra'],
            ['name' => 'Ambarnath', 'state' => 'Maharashtra'],
            ['name' => 'Bhusawal', 'state' => 'Maharashtra'],
            ['name' => 'Badlapur', 'state' => 'Maharashtra'],
            ['name' => 'Ratnagiri', 'state' => 'Maharashtra'],
            ['name' => 'Gondia', 'state' => 'Maharashtra'],
            ['name' => 'Satara', 'state' => 'Maharashtra'],
            ['name' => 'Barshi', 'state' => 'Maharashtra'],
            ['name' => 'Yavatmal', 'state' => 'Maharashtra'],
            ['name' => 'Achalpur', 'state' => 'Maharashtra'],
            ['name' => 'Osmanabad', 'state' => 'Maharashtra'],
            ['name' => 'Nandurbar', 'state' => 'Maharashtra'],
            ['name' => 'Wardha', 'state' => 'Maharashtra'],
            ['name' => 'Udgir', 'state' => 'Maharashtra'],
            ['name' => 'Hinganghat', 'state' => 'Maharashtra'],
            ['name' => 'Karad', 'state' => 'Maharashtra'],
            ['name' => 'Chiplun', 'state' => 'Maharashtra'],
            ['name' => 'Sangamner', 'state' => 'Maharashtra'],
            ['name' => 'Palghar', 'state' => 'Maharashtra'],
            ['name' => 'Virar', 'state' => 'Maharashtra'],
            ['name' => 'Nala Sopara', 'state' => 'Maharashtra'],
            ['name' => 'Badlapur', 'state' => 'Maharashtra'],
            ['name' => 'Dombivli', 'state' => 'Maharashtra'],
            ['name' => 'Kalyan', 'state' => 'Maharashtra'],
            ['name' => 'Titwala', 'state' => 'Maharashtra'],
            ['name' => 'Asangaon', 'state' => 'Maharashtra'],
            ['name' => 'Kasara', 'state' => 'Maharashtra'],
            ['name' => 'Karjat', 'state' => 'Maharashtra'],
            ['name' => 'Khopoli', 'state' => 'Maharashtra'],
            ['name' => 'Lonavla', 'state' => 'Maharashtra'],
            ['name' => 'Talegaon', 'state' => 'Maharashtra'],
            ['name' => 'Chakan', 'state' => 'Maharashtra'],
            ['name' => 'Shirur', 'state' => 'Maharashtra'],
            ['name' => 'Baramati', 'state' => 'Maharashtra'],
            ['name' => 'Phaltan', 'state' => 'Maharashtra'],
            ['name' => 'Beed', 'state' => 'Maharashtra'],
            ['name' => 'Buldhana', 'state' => 'Maharashtra'],
            ['name' => 'Washim', 'state' => 'Maharashtra'],
            ['name' => 'Hingoli', 'state' => 'Maharashtra'],
            ['name' => 'Gadchiroli', 'state' => 'Maharashtra'],
            ['name' => 'Bhandara', 'state' => 'Maharashtra'],
            ['name' => 'Sawantwadi', 'state' => 'Maharashtra'],
            ['name' => 'Malvan', 'state' => 'Maharashtra'],
            ['name' => 'Kudal', 'state' => 'Maharashtra'],
            ['name' => 'Kankavli', 'state' => 'Maharashtra'],
            ['name' => 'Alibag', 'state' => 'Maharashtra'],
            ['name' => 'Pen', 'state' => 'Maharashtra'],
            ['name' => 'Mahad', 'state' => 'Maharashtra'],
            ['name' => 'Roha', 'state' => 'Maharashtra'],
            ['name' => 'Mangaon', 'state' => 'Maharashtra'],
            ['name' => 'Boisar', 'state' => 'Maharashtra'],
            ['name' => 'Dahanu', 'state' => 'Maharashtra'],
            ['name' => 'Manchar', 'state' => 'Maharashtra'],
            ['name' => 'Narayangaon', 'state' => 'Maharashtra'],
            ['name' => 'Junner', 'state' => 'Maharashtra'],
            ['name' => 'Shrirampur', 'state' => 'Maharashtra'],
            ['name' => 'Kopargaon', 'state' => 'Maharashtra'],
            ['name' => 'Shirdi', 'state' => 'Maharashtra'],
            ['name' => 'Rahuri', 'state' => 'Maharashtra'],
            ['name' => 'Sangola', 'state' => 'Maharashtra'],
            ['name' => 'Pandharpur', 'state' => 'Maharashtra'],
            ['name' => 'Akluj', 'state' => 'Maharashtra'],
            ['name' => 'Malshapuras', 'state' => 'Maharashtra'],
            ['name' => 'Shegaon', 'state' => 'Maharashtra'],
            ['name' => 'Khamgaon', 'state' => 'Maharashtra'],
            ['name' => 'Malkapur', 'state' => 'Maharashtra'],
            ['name' => 'Tumsar', 'state' => 'Maharashtra'],
            ['name' => 'Pauni', 'state' => 'Maharashtra'],
            ['name' => 'Warora', 'state' => 'Maharashtra'],
            ['name' => 'Ballarpur', 'state' => 'Maharashtra'],
            ['name' => 'Gadhinglaj', 'state' => 'Maharashtra'],
            ['name' => 'Halkarni', 'state' => 'Maharashtra'],
            ['name' => 'Ajara', 'state' => 'Maharashtra'],
            ['name' => 'Chandgad', 'state' => 'Maharashtra'],

            // DELHI & NCR
            ['name' => 'Delhi', 'state' => 'Delhi'],
            ['name' => 'New Delhi', 'state' => 'Delhi'],
            ['name' => 'Noida', 'state' => 'Uttar Pradesh'],
            ['name' => 'Greater Noida', 'state' => 'Uttar Pradesh'],
            ['name' => 'Gurgaon', 'state' => 'Haryana'],
            ['name' => 'Faridabad', 'state' => 'Haryana'],
            ['name' => 'Ghaziabad', 'state' => 'Uttar Pradesh'],

            // KARNATAKA
            ['name' => 'Bangalore', 'state' => 'Karnataka'],
            ['name' => 'Hubballi-Dharwad', 'state' => 'Karnataka'],
            ['name' => 'Mysuru', 'state' => 'Karnataka'],
            ['name' => 'Kalaburagi', 'state' => 'Karnataka'],
            ['name' => 'Mangaluru', 'state' => 'Karnataka'],
            ['name' => 'Belagavi', 'state' => 'Karnataka'],
            ['name' => 'Davanagere', 'state' => 'Karnataka'],
            ['name' => 'Ballari', 'state' => 'Karnataka'],
            ['name' => 'Vijayapura', 'state' => 'Karnataka'],
            ['name' => 'Shivamogga', 'state' => 'Karnataka'],
            ['name' => 'Tumakuru', 'state' => 'Karnataka'],
            ['name' => 'Raichur', 'state' => 'Karnataka'],

            // TAMIL NADU
            ['name' => 'Chennai', 'state' => 'Tamil Nadu'],
            ['name' => 'Coimbatore', 'state' => 'Tamil Nadu'],
            ['name' => 'Madurai', 'state' => 'Tamil Nadu'],
            ['name' => 'Tiruchirappalli', 'state' => 'Tamil Nadu'],
            ['name' => 'Salem', 'state' => 'Tamil Nadu'],
            ['name' => 'Tirunelveli', 'state' => 'Tamil Nadu'],
            ['name' => 'Tiruppur', 'state' => 'Tamil Nadu'],
            ['name' => 'Erode', 'state' => 'Tamil Nadu'],
            ['name' => 'Vellore', 'state' => 'Tamil Nadu'],
            ['name' => 'Thoothukudi', 'state' => 'Tamil Nadu'],
            ['name' => 'Nagercoil', 'state' => 'Tamil Nadu'],
            ['name' => 'Thanjavur', 'state' => 'Tamil Nadu'],

            // TELANGANA & ANDHRA PRADESH
            ['name' => 'Hyderabad', 'state' => 'Telangana'],
            ['name' => 'Warangal', 'state' => 'Telangana'],
            ['name' => 'Nizamabad', 'state' => 'Telangana'],
            ['name' => 'Karimnagar', 'state' => 'Telangana'],
            ['name' => 'Visakhapatnam', 'state' => 'Andhra Pradesh'],
            ['name' => 'Vijayawada', 'state' => 'Andhra Pradesh'],
            ['name' => 'Guntur', 'state' => 'Andhra Pradesh'],
            ['name' => 'Nellore', 'state' => 'Andhra Pradesh'],
            ['name' => 'Kurnool', 'state' => 'Andhra Pradesh'],
            ['name' => 'Rajahmundry', 'state' => 'Andhra Pradesh'],
            ['name' => 'Tirupati', 'state' => 'Andhra Pradesh'],
            ['name' => 'Kakinada', 'state' => 'Andhra Pradesh'],

            // UTTAR PRADESH
            ['name' => 'Lucknow', 'state' => 'Uttar Pradesh'],
            ['name' => 'Kanpur', 'state' => 'Uttar Pradesh'],
            ['name' => 'Agra', 'state' => 'Uttar Pradesh'],
            ['name' => 'Varanasi', 'state' => 'Uttar Pradesh'],
            ['name' => 'Meerut', 'state' => 'Uttar Pradesh'],
            ['name' => 'Prayagraj', 'state' => 'Uttar Pradesh'],
            ['name' => 'Bareilly', 'state' => 'Uttar Pradesh'],
            ['name' => 'Aligarh', 'state' => 'Uttar Pradesh'],
            ['name' => 'Moradabad', 'state' => 'Uttar Pradesh'],
            ['name' => 'Saharanpur', 'state' => 'Uttar Pradesh'],
            ['name' => 'Gorakhpur', 'state' => 'Uttar Pradesh'],
            ['name' => 'Firozabad', 'state' => 'Uttar Pradesh'],
            ['name' => 'Jhansi', 'state' => 'Uttar Pradesh'],
            ['name' => 'Muzaffarnagar', 'state' => 'Uttar Pradesh'],
            ['name' => 'Mathura', 'state' => 'Uttar Pradesh'],

            // RAJASTHAN
            ['name' => 'Jaipur', 'state' => 'Rajasthan'],
            ['name' => 'Jodhpur', 'state' => 'Rajasthan'],
            ['name' => 'Kota', 'state' => 'Rajasthan'],
            ['name' => 'Bikaner', 'state' => 'Rajasthan'],
            ['name' => 'Ajmer', 'state' => 'Rajasthan'],
            ['name' => 'Udaipur', 'state' => 'Rajasthan'],
            ['name' => 'Bhilwara', 'state' => 'Rajasthan'],
            ['name' => 'Alwar', 'state' => 'Rajasthan'],
            ['name' => 'Sikar', 'state' => 'Rajasthan'],
            ['name' => 'Pali', 'state' => 'Rajasthan'],

            // MADHYA PRADESH
            ['name' => 'Indore', 'state' => 'Madhya Pradesh'],
            ['name' => 'Bhopal', 'state' => 'Madhya Pradesh'],
            ['name' => 'Jabalpur', 'state' => 'Madhya Pradesh'],
            ['name' => 'Gwalior', 'state' => 'Madhya Pradesh'],
            ['name' => 'Ujjain', 'state' => 'Madhya Pradesh'],
            ['name' => 'Sagar', 'state' => 'Madhya Pradesh'],
            ['name' => 'Ratlam', 'state' => 'Madhya Pradesh'],
            ['name' => 'Rewa', 'state' => 'Madhya Pradesh'],
            ['name' => 'Satna', 'state' => 'Madhya Pradesh'],
            ['name' => 'Dewas', 'state' => 'Madhya Pradesh'],

            // WEST BENGAL
            ['name' => 'Kolkata', 'state' => 'West Bengal'],
            ['name' => 'Howrah', 'state' => 'West Bengal'],
            ['name' => 'Siliguri', 'state' => 'West Bengal'],
            ['name' => 'Durgapur', 'state' => 'West Bengal'],
            ['name' => 'Asansol', 'state' => 'West Bengal'],
            ['name' => 'Maheshtala', 'state' => 'West Bengal'],
            ['name' => 'Rajpur Sonarpur', 'state' => 'West Bengal'],
            ['name' => 'Berhampore', 'state' => 'West Bengal'],

            // PUNJAB & HARYANA
            ['name' => 'Ludhiana', 'state' => 'Punjab'],
            ['name' => 'Amritsar', 'state' => 'Punjab'],
            ['name' => 'Jalandhar', 'state' => 'Punjab'],
            ['name' => 'Patiala', 'state' => 'Punjab'],
            ['name' => 'Bathinda', 'state' => 'Punjab'],
            ['name' => 'SAS Nagar', 'state' => 'Punjab'],
            ['name' => 'Chandigarh', 'state' => 'Chandigarh'],
            ['name' => 'Hisar', 'state' => 'Haryana'],
            ['name' => 'Panipat', 'state' => 'Haryana'],
            ['name' => 'Karnal', 'state' => 'Haryana'],
            ['name' => 'Rohtak', 'state' => 'Haryana'],
            ['name' => 'Sonipat', 'state' => 'Haryana'],

            // BIHAR & JHARKHAND
            ['name' => 'Patna', 'state' => 'Bihar'],
            ['name' => 'Gaya', 'state' => 'Bihar'],
            ['name' => 'Bhagalpur', 'state' => 'Bihar'],
            ['name' => 'Muzaffarpur', 'state' => 'Bihar'],
            ['name' => 'Purnia', 'state' => 'Bihar'],
            ['name' => 'Ranchi', 'state' => 'Jharkhand'],
            ['name' => 'Jamshedpur', 'state' => 'Jharkhand'],
            ['name' => 'Dhanbad', 'state' => 'Jharkhand'],
            ['name' => 'Bokaro Steel City', 'state' => 'Jharkhand'],

            // OTHER STATES
            ['name' => 'Bhubaneswar', 'state' => 'Odisha'],
            ['name' => 'Cuttack', 'state' => 'Odisha'],
            ['name' => 'Rourkela', 'state' => 'Odisha'],
            ['name' => 'Raipur', 'state' => 'Chhattisgarh'],
            ['name' => 'Bhilai', 'state' => 'Chhattisgarh'],
            ['name' => 'Bilaspur', 'state' => 'Chhattisgarh'],
            ['name' => 'Thiruvananthapuram', 'state' => 'Kerala'],
            ['name' => 'Kochi', 'state' => 'Kerala'],
            ['name' => 'Kozhikode', 'state' => 'Kerala'],
            ['name' => 'Dehradun', 'state' => 'Uttarakhand'],
            ['name' => 'Haridwar', 'state' => 'Uttarakhand'],
            ['name' => 'Guwahati', 'state' => 'Assam'],
            ['name' => 'Jammu', 'state' => 'Jammu and Kashmir'],
            ['name' => 'Srinagar', 'state' => 'Jammu and Kashmir'],
            ['name' => 'Shimla', 'state' => 'Himachal Pradesh'],
            ['name' => 'Panaji', 'state' => 'Goa'],
            ['name' => 'Puducherry', 'state' => 'Puducherry'],
            ['name' => 'Itanagar', 'state' => 'Arunachal Pradesh'],
            ['name' => 'Imphal', 'state' => 'Manipur'],
            ['name' => 'Shillong', 'state' => 'Meghalaya'],
            ['name' => 'Aizawl', 'state' => 'Mizoram'],
            ['name' => 'Kohima', 'state' => 'Nagaland'],
            ['name' => 'Agartala', 'state' => 'Tripura'],
            ['name' => 'Gangtok', 'state' => 'Sikkim'],
        ];

        foreach ($cities as $city) {
            \App\Models\City::updateOrCreate(
                ['name' => $city['name']],
                [
                    'state' => $city['state'],
                    'slug' => \Illuminate\Support\Str::slug($city['name']),
                    'is_active' => true
                ]
            );
        }
    }
}
